// Util generated by AI. use for testing reactivity
export function shuffleString(text: string): string {
	if (!text || text.length <= 1) {
		return text;
	}

	const characters: string[] = text.split("");

	for (let i: number = characters.length - 1; i > 0; i--) {
		const j: number = Math.floor(Math.random() * (i + 1));

		// 1. Extract elements into safe constants
		const itemI = characters[i];
		const itemJ = characters[j];

		// 2. Type guard to satisfy 'noUncheckedIndexedAccess'
		if (itemI !== undefined && itemJ !== undefined) {
			characters[i] = itemJ;
			characters[j] = itemI;
		}
	}

	return characters.join("");
}
